version: "3.9"
services:
  sql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - smarterplay_sql:/var/lib/mysql
    env_file:
      vars.env
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 5s
        retries: 10
  node:
    depends_on:
      sql:
        condition: service_healthy
    build:
      context: .
    ports:
      - 8080:8080
    env_file:
     vars.env
    volumes:
      - ./lib:/code/lib
      - ./migrations:/code/migrations
volumes:
  smarterplay_sql:
